### ISSUE TITLE
The logback library should neither form a compile nor runtime dependency

### ISSUE THREAD

**Issue by meincs** [FraunhoferIOSB/SensorThings-SweCommon#1]
A library should never be linked to a specific logging framework implementation. Instead a library links to a certain logging API, e.g. slf4j. It should be under the repsoibility of the application, that makes use of the library, which logging framework to use, e.g. logback, log4j or whatever else.

Since the SensorThings-SweCommon itself provides some kind of application (e.g. gui part), it may make sense to split the entire library into two parts, e.g. a library and tool.

**Comment by hylkevds** [comment]
Yep, you are correct.

**Comment by hylkevds** [comment]
Logback was removed in 0.3.
